### ISSUE TITLE
Project has no LICENSE

### ISSUE THREAD

**Issue by aschrijver** [Alamantus/little-library#6]
I am creating a new _developer resources_ page for the [Feneas wiki research area](https://git.feneas.org/feneas/fediverse/-/wikis/Home) and noticed that your project has no LICENSE, which technically makes it proprietary and not open-source.

On the [ActivityPub watchlist](https://git.feneas.org/feneas/fediverse/-/wikis/watchlist-for-activitypub-apps) you were in the 'Developer tools' section, but I have moved you to 'Blog, Publishing, and Reading Apps'. Having a license is essential though for inclusion, as we only track open source (I'll attach a link to this issue).

Also your ActivityPub support, when it works and federates with other Fediverse apps, are an important feature that you should really, proudly advertise as well as document on the README more clearly, IMHO :) 

Furthermore I'd add some Github topics to the repo for findability e.g. 'activitypub', 'fediverse', 'e-book', 'library' etc.

**Comment by Alamantus** [comment]
@aschrijver Thanks! I'll work on getting a license up as soon as I'm able.

Adding it to the ActivityPub watchlist is a little bit premature, because I still have a little bit of work to do before it federates appropriately, but that would probably be the correct category—I'm not sure who added it originally. At the moment, AP support is just in a separate activitypub branch that I'm still working on. :)

**Comment by aschrijver** [comment]
The watchlist is for monitoring ongoing status. Once there is a certain level of readiness/maturity things will be listed on https://fediverse.party

**Comment by Alamantus** [comment]
@aschrijver I've added the GNU AGPLv3 license to the project because my previous research into open source licenses, that seemed to be the way to go for what I wanted (free use but no closing the source and selling it)

As for ActivityPub support, I will hopefully be able to get back into working on it soon! I just need to be able to correctly validate follow accept activities and set it up to send activities to followers!

**Comment by aschrijver** [comment]
Super! I have update your project description on the AP watchlist.
